openapi: 3.1.0
info:
  title: Data Space Search Service
  description: The service provides a REST API for searching catalog items.
  contact:
    name: HIRO-MicroDataCenters
    email: all-hiro@hiro-microdatacenters.nl
  license:
    name: MIT
    url: https://github.com/HIRO-MicroDataCenters-BV/ds-catalog/blob/main/LICENSE
  version: 0.1.1
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health-check/:
    get:
      summary: Health check
      description: Returns a 200 status code if the service is up and running
      operationId: health_check
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
  /search/:
    post:
      tags:
      - Decentralized Search
      summary: Search catalog items across catalogs
      description: "Search across the catalogs in decentralized way for filters documentation, you can check it here https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
      operationId: search_catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogFilters'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: object
                  '@graph':
                    type: array
                    items:
                      type: object
              example:
                '@context':
                  xsd: http://www.w3.org/2001/XMLSchema#
                  dcat: http://www.w3.org/ns/dcat#
                  dcatap: http://data.europa.eu/r5r/
                  dcterms: http://purl.org/dc/terms/
                  spdx: http://spdx.org/rdf/terms#
                  foaf: http://xmlns.com/foaf/0.1/
                  skos: http://www.w3.org/2004/02/skos/core#
                  dspace: http://data-space.org/
                '@graph':
                - '@id': https://example.com/catalog/123
                  '@type': dcat:Catalog
                  dcterms:title:
                  - '@language': en
                    '@value': Sample Catalog
                  'other fields': "For all the other fields follow this documentation https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
                - '@id': https://example.com/catalog/124
                  '@type': dcat:Catalog
                  dcterms:title:
                  - '@language': en
                    '@value': Another Sample Catalog
                  'other fields': "For all the other fields follow this documentation https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
                  
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /search-catalog/:
    post:
      tags:
      - Local Search
      summary: Search Local Catalog
      description: "Search the local catalog with dataset list.for filters documentation, you can check it here https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
      operationId: search_catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogFilters'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/ld+json:
              schema:
                type: string
              example:
                '@context':
                  '@vocab': http://data-space.org/
                  xsd: http://www.w3.org/2001/XMLSchema#
                  dcat: http://www.w3.org/ns/dcat#
                  dcatap: http://data.europa.eu/r5r/
                  dcterms: http://purl.org/dc/terms/
                  spdx: http://spdx.org/rdf/terms#
                  foaf: http://xmlns.com/foaf/0.1/
                  skos: http://www.w3.org/2004/02/skos/core#
                '@id': https://example.com/catalog/123
                '@type': dcat:Catalog
                dcterms:title:
                  '@language': en
                  '@value': Sample Catalog
                'other fields': "For all the other fields follow this documentation https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"

        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    CatalogFilters:
      description: "you can find the documentation here https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
      additionalProperties: true
      type: object
      title: CatalogFilters

    Dataset:
      properties:
        '@context':
          type: object
          title: '@Context'
      additionalProperties: true
      type: object
      title: Dataset
      examples:
      - '@context':
          dcat: http://www.w3.org/ns/dcat#
          dcatap: http://data.europa.eu/r5r/
          dcterms: http://purl.org/dc/terms/
          dspace: http://data-space.org/
          foaf: http://xmlns.com/foaf/0.1/
          skos: http://www.w3.org/2004/02/skos/core#
          spdx: http://spdx.org/rdf/terms#
          xsd: http://www.w3.org/2001/XMLSchema#
        '@id': https://example.com/dataset/789
        '@type': dcat:Dataset
        dcat:distribution:
        - '@id': https://example.com/distribution/489
          '@type': dcat:Distribution
          dcat:accessService:
          - '@id': https://example.com/dataservice/456
            '@type': dcat:DataService
            dcat:endpointURL:
              '@id': https://example.com/dataservice/456/download
            dcterms:title:
            - '@language': en
              '@value': Sample Data Service
          dcat:accessURL:
            '@id': https://example.com/distribution/489/information
          dcat:byteSize:
            '@type': xsd:decimal
            '@value': 1024
          dcat:format: JSON
          dcat:mediaType:
            '@id': https://www.iana.org/assignments/media-types/application/json
          dcatap:availability:
          - '@id': http://data.europa.eu/r5r/AVAILABLE
          dcterms:description:
          - '@language': en
            '@value': This is a sample distribution.
          spdx:checksum:
            spdx:algorithm: SHA-256
            spdx:checksumValue: 3a7bd3e2360a3b5c1b2ef3b1a4e8f7a6
        dcat:keyword:
        - sample
        - data
        dcat:theme:
        - '@id': http://eurovoc.europa.eu/100142
          '@type': skos:Concept
          skos:prefLabel:
          - '@language': en
            '@value': Agriculture
        - '@id': http://eurovoc.europa.eu/100141
          '@type': skos:Concept
          skos:prefLabel:
          - '@language': en
            '@value': Health
        dcterms:description:
        - '@language': en
          '@value': This dataset contains sample data for testing purposes.
        - '@language': es
          '@value': Este conjunto de datos contiene datos de ejemplo para fines de
            prueba.
        dcterms:identifier: abc-123-xyz
        dcterms:license: https://example.com/license/xyz
        dcterms:title:
        - '@language': en
          '@value': Sample Dataset Title
        - '@language': es
          '@value': "T\xEDtulo del conjunto de datos de ejemplo"
        dspace:extraMetadata:
        - '@id': https://example.com/metadata/1
          '@type': med:Patient
          med:birthDate: '1990-05-20'
          med:height:
            '@type': xsd:integer
            '@value': '180'
          med:sex: M
          med:weight:
            '@type': xsd:integer
            '@value': '75'
        - '@id': https://example.com/metadata/2
          '@type': med:Diagnoses
          med:hasDiagnosis:
          - '@id': https://example.com/diagnosis/1
            '@type': med:Diagnosis
            med:code: I10
            med:description: Essential (primary) hypertension
          - '@id': https://example.com/diagnosis/2
            '@type': med:Diagnosis
            med:code: E11
            med:description: Type 2 diabetes mellitus
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HealthCheck:
      properties:
        status:
          type: string
          title: Status
          examples:
          - OK
      type: object
      required:
      - status
      title: HealthCheck
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError