openapi: 3.1.0
info:
  title: Data Space Search Service
  description: The service provides a REST API for searching catalog items.
  contact:
    name: HIRO-MicroDataCenters
    email: all-hiro@hiro-microdatacenters.nl
  license:
    name: MIT
    url: https://github.com/HIRO-MicroDataCenters-BV/ds-catalog/blob/main/LICENSE
  version: 0.1.1
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health-check/:
    get:
      summary: Health check
      description: Returns a 200 status code if the service is up and running
      operationId: health_check
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
  /catalog/:
    post:
      tags:
      - Catalog
      summary: Get Local Catalog
      description: "Get the local catalog with dataset list.\n\nThe request accepts\
        \ filters as a JSON-LD object in the body.\n\n### Format:\nFilters are structured\
        \ as nested JSON-LD objects. Each filter defines the path\nto the field with\
        \ optional operators or language annotations.\n\n```json\n{\n  \"@context\"\
        : {\n    \"@vocab\": \"http://data-space.org/\",\n    \"<namespace>\": \"\
        <namespaceURL>\",\n    ...\n  }\n  \"filters\": [\n    {\n      [\"@type\"\
        : \"<[namespace:]Class>\",]\n      \"<[namespace:]attribute>[@<lang>]\": <nestedObject>\
        \ | <value> | {\n        \"operation\": \"<operator>\",\n        \"operationValue\"\
        : <value>\n      }\n    },\n    ...\n  ]\n}\n```\n\n### Supported operators:\n\
        - `gte`, `lte` \u2014 range filtering\n- `in` \u2014 list filtering\n- `contains`\
        \ \u2014 substring search\n\n### Example:\n```json\n{\n  \"@context\": {\n\
        \    \"@vocab\": \"http://data-space.org/\",\n    \"dcat\": \"http://www.w3.org/ns/dcat#\"\
        ,\n    \"med\": \"http://med.example.org/\"\n  },\n  \"filters\": [\n    {\n\
        \      \"dcat:dataset\": {\n        \"extraMetadata\": {\n          \"@type\"\
        : \"med:Diagnoses\",\n          \"med:hasDiagnosis\": {\n            \"med:code\"\
        : {\n              \"operation\": \"contains\",\n              \"operationValue\"\
        : \"I10\"\n            }\n          }\n        }\n      }\n    }\n  ]\n}\n\
        ```\n\n### More filter examples:\n- ```json\n    {\n        \"dcat:dataset\"\
        : {\n            \"dcterms:title\": \"example\"\n        }\n    }\n  ```\n\
        - ```json\n    {\n        \"dcat:dataset\": {\n            \"dcterms:title@en\"\
        : \"example\"\n        }\n    }\n  ```\n- ```json\n    {\n        \"dcat:dataset\"\
        : {\n            \"dcterms:title\": {\n                \"@language\": \"en\"\
        \n            }\n        }\n    }\n  ```\n- ```json\n    {\n        \"dcat:dataset\"\
        : {\n            \"dcterms:title\": {\n                \"@value\": \"example\"\
        \n            }\n        }\n    }\n  ```\n- ```json\n    {\n        \"dcat:dataset\"\
        : {\n            \"dcat:distribution\": {\n                \"dcat:format\"\
        : \"PDF\"\n            }\n        }\n    }\n  ```\n- ```json\n    {\n    \
        \    \"dcat:dataset\": {\n            \"extraMetadata\": {\n             \
        \   \"med:sex\": \"M\"\n            }\n        }\n    }\n  ```\n- ```json\n\
        \    {\n        \"dcat:dataset\": {\n            \"extraMetadata\": {\n  \
        \              \"@type\": \"med:Patient\",\n                \"med:sex\": \"\
        M\"\n            }\n        }\n    }\n  ```\n- ```json\n    {\n        \"\
        dcat:dataset\": {\n            \"extraMetadata\": {\n                \"med:weight\"\
        : 75\n            }\n        }\n    }\n  ```\n- ```json\n    {\n        \"\
        dcat:dataset\": {\n            \"extraMetadata\": {\n                \"med:weight\"\
        : {\n                    \"@value\": 75\n                }\n            }\n\
        \        }\n    }\n  ```\n- ```json\n    {\n        \"dcat:dataset\": {\n\
        \            \"extraMetadata\": {\n                \"med:weight\": {\n   \
        \                 \"@type\": \"xsd:integer\"\n                }\n        \
        \    }\n        }\n    }\n  ```\n- ```json\n    {\n        \"dcat:dataset\"\
        : {\n            \"dcterms:datePublished\": {\n                \"operationValue\"\
        : \"2021-01-01\",\n                \"operation\": \"gte\"\n            }\n\
        \        }\n    }\n  ```\n- ```json\n    {\n        \"dcat:dataset\": {\n\
        \            \"dcterms:datePublished\": {\n                \"operationValue\"\
        : \"2021-12-31\",\n                \"operation\": \"lte\"\n            }\n\
        \        }\n    }\n  ```\n- ```json\n    {\n        \"dcat:dataset\": {\n\
        \            \"extraMetadata\": {\n                \"med:weight\": {\n   \
        \                 \"operationValue\": 70,\n                    \"operation\"\
        : \"gte\"\n                }\n            }\n        }\n    }\n  ```\n- ```json\n\
        \    {\n        \"dcat:dataset\": {\n            \"extraMetadata\": {\n  \
        \              \"med:weight\": {\n                    \"operationValue\":\
        \ 70,\n                    \"operation\": \"lte\"\n                }\n   \
        \         }\n        }\n    }\n  ```\n- ```json\n    {\n        \"dcat:dataset\"\
        : {\n            \"dcat:keyword\": {\n                \"operationValue\":\
        \ [\"science\", \"health\"],\n                \"operation\": \"in\"\n    \
        \        }\n        }\n    }\n  ```\n- ```json\n    {\n        \"dcat:dataset\"\
        : {\n            \"dcterms:title@en\": {\n                \"operationValue\"\
        : \"example\",\n                \"operation\": \"contains\"\n            }\n\
        \        }\n    }\n  ```"
      operationId: get_catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogFilters'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/ld+json:
              schema:
                type: string
              example:
                '@context':
                  xsd: http://www.w3.org/2001/XMLSchema#
                  dcat: http://www.w3.org/ns/dcat#
                  dcatap: http://data.europa.eu/r5r/
                  dcterms: http://purl.org/dc/terms/
                  spdx: http://spdx.org/rdf/terms#
                  foaf: http://xmlns.com/foaf/0.1/
                  skos: http://www.w3.org/2004/02/skos/core#
                  dspace: http://data-space.org/
                '@id': https://example.com/catalog/123
                '@type': dcat:Catalog
                dcterms:title:
                - '@language': en
                  '@value': Sample Catalog
                dcterms:description:
                - '@language': en
                  '@value': This is a sample catalog containing various datasets and
                    services.
                dcterms:publisher:
                  '@id': https://example.com/person/123
                  '@type': foaf:Agent
                  foaf:name: John Doe
                dcat:dataset:
                - '@id': https://example.com/dataset/789
                  '@type': dcat:Dataset
                  dcterms:identifier: abc-123-xyz
                  dcterms:title:
                  - '@language': en
                    '@value': Sample Dataset Title
                  - '@language': es
                    '@value': "T\xEDtulo del conjunto de datos de ejemplo"
                  dcterms:description:
                  - '@language': en
                    '@value': This dataset contains sample data for testing purposes.
                  - '@language': es
                    '@value': Este conjunto de datos contiene datos de ejemplo para
                      fines de prueba.
                  dcat:keyword:
                  - sample
                  - data
                  dcterms:license: https://example.com/license/xyz
                  dcat:theme:
                  - '@id': http://eurovoc.europa.eu/100142
                    '@type': skos:Concept
                    skos:prefLabel:
                    - '@value': Agriculture
                      '@language': en
                  - '@id': http://eurovoc.europa.eu/100141
                    '@type': skos:Concept
                    skos:prefLabel:
                    - '@value': Health
                      '@language': en
                  dcat:distribution:
                  - '@id': https://example.com/distribution/489
                    '@type': dcat:Distribution
                    dcterms:description:
                    - '@language': en
                      '@value': This is a sample distribution.
                    dcat:byteSize:
                      '@value': 1024
                      '@type': xsd:decimal
                    dcat:mediaType:
                      '@id': https://www.iana.org/assignments/media-types/application/json
                    dcat:format: JSON
                    dcatap:availability:
                    - '@id': http://data.europa.eu/r5r/AVAILABLE
                    spdx:checksum:
                      spdx:algorithm: SHA-256
                      spdx:checksumValue: 3a7bd3e2360a3b5c1b2ef3b1a4e8f7a6
                    dcat:accessURL:
                      '@id': https://example.com/distribution/489/information
                    dcat:accessService:
                    - '@id': https://example.com/dataservice/456
                      '@type': dcat:DataService
                      dcterms:title:
                      - '@language': en
                        '@value': Sample Data Service
                      dcat:endpointURL:
                        '@id': https://example.com/dataservice/456/download
                  dcat:inSeries:
                    '@id': string
                  dspace:extraMetadata:
                  - '@id': https://example.com/metadata/1
                    '@type': med:Patient
                    med:height:
                      '@value': '180'
                      '@type': xsd:integer
                    med:weight:
                      '@value': '75'
                      '@type': xsd:integer
                    med:sex: M
                    med:birthDate: '1990-05-20'
                  - '@id': https://example.com/metadata/2
                    '@type': med:Diagnoses
                    med:hasDiagnosis:
                    - '@id': https://example.com/diagnosis/1
                      '@type': med:Diagnosis
                      med:code: I10
                      med:description: Essential (primary) hypertension
                    - '@id': https://example.com/diagnosis/2
                      '@type': med:Diagnosis
                      med:code: E11
                      med:description: Type 2 diabetes mellitus
                  dcterms:issued: '2025-03-13'
                  dcterms:publisher:
                    '@id': https://example.com/person/123
                    '@type': foaf:Agent
                    foaf:name: John Doe
                  dspace:isShared: true
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

    post:
      tags:
      - Sharing
      summary: Unhare Dataset
      description: Unshare a dataset
      operationId: unshare_dataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      responses:
        '204':
          description: Successful Response
        '404':
          description: Dataset not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    CatalogFilters:
      properties:
        '@context':
          type: object
          title: '@Context'
        filters:
          items:
            type: object
          type: array
          title: Filters
      additionalProperties: true
      type: object
      title: CatalogFilters
      examples:
      - '@context':
          '@vocab': http://data-space.org/
          dcat: http://www.w3.org/ns/dcat#
          med: http://med.example.org/
        filters:
        - dcat:dataset:
            extraMetadata:
              '@type': med:Diagnoses
              med:hasDiagnosis:
                med:code:
                  operation: contains
                  operationValue: I10
    Dataset:
      properties:
        '@context':
          type: object
          title: '@Context'
      additionalProperties: true
      type: object
      title: Dataset
      examples:
      - '@context':
          dcat: http://www.w3.org/ns/dcat#
          dcatap: http://data.europa.eu/r5r/
          dcterms: http://purl.org/dc/terms/
          dspace: http://data-space.org/
          foaf: http://xmlns.com/foaf/0.1/
          skos: http://www.w3.org/2004/02/skos/core#
          spdx: http://spdx.org/rdf/terms#
          xsd: http://www.w3.org/2001/XMLSchema#
        '@id': https://example.com/dataset/789
        '@type': dcat:Dataset
        dcat:distribution:
        - '@id': https://example.com/distribution/489
          '@type': dcat:Distribution
          dcat:accessService:
          - '@id': https://example.com/dataservice/456
            '@type': dcat:DataService
            dcat:endpointURL:
              '@id': https://example.com/dataservice/456/download
            dcterms:title:
            - '@language': en
              '@value': Sample Data Service
          dcat:accessURL:
            '@id': https://example.com/distribution/489/information
          dcat:byteSize:
            '@type': xsd:decimal
            '@value': 1024
          dcat:format: JSON
          dcat:mediaType:
            '@id': https://www.iana.org/assignments/media-types/application/json
          dcatap:availability:
          - '@id': http://data.europa.eu/r5r/AVAILABLE
          dcterms:description:
          - '@language': en
            '@value': This is a sample distribution.
          spdx:checksum:
            spdx:algorithm: SHA-256
            spdx:checksumValue: 3a7bd3e2360a3b5c1b2ef3b1a4e8f7a6
        dcat:keyword:
        - sample
        - data
        dcat:theme:
        - '@id': http://eurovoc.europa.eu/100142
          '@type': skos:Concept
          skos:prefLabel:
          - '@language': en
            '@value': Agriculture
        - '@id': http://eurovoc.europa.eu/100141
          '@type': skos:Concept
          skos:prefLabel:
          - '@language': en
            '@value': Health
        dcterms:description:
        - '@language': en
          '@value': This dataset contains sample data for testing purposes.
        - '@language': es
          '@value': Este conjunto de datos contiene datos de ejemplo para fines de
            prueba.
        dcterms:identifier: abc-123-xyz
        dcterms:license: https://example.com/license/xyz
        dcterms:title:
        - '@language': en
          '@value': Sample Dataset Title
        - '@language': es
          '@value': "T\xEDtulo del conjunto de datos de ejemplo"
        dspace:extraMetadata:
        - '@id': https://example.com/metadata/1
          '@type': med:Patient
          med:birthDate: '1990-05-20'
          med:height:
            '@type': xsd:integer
            '@value': '180'
          med:sex: M
          med:weight:
            '@type': xsd:integer
            '@value': '75'
        - '@id': https://example.com/metadata/2
          '@type': med:Diagnoses
          med:hasDiagnosis:
          - '@id': https://example.com/diagnosis/1
            '@type': med:Diagnosis
            med:code: I10
            med:description: Essential (primary) hypertension
          - '@id': https://example.com/diagnosis/2
            '@type': med:Diagnosis
            med:code: E11
            med:description: Type 2 diabetes mellitus
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HealthCheck:
      properties:
        status:
          type: string
          title: Status
          examples:
          - OK
      type: object
      required:
      - status
      title: HealthCheck
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
