openapi: 3.1.0
info:
  title: Data Space Search Service
  description: The service provides a REST API for searching catalog items.
  contact:
    name: HIRO-MicroDataCenters
    email: all-hiro@hiro-microdatacenters.nl
  license:
    name: MIT
    url: https://github.com/HIRO-MicroDataCenters-BV/ds-catalog/blob/main/LICENSE
  version: 0.1.1
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health-check/:
    get:
      summary: Health check
      description: Returns a 200 status code if the service is up and running
      operationId: health_check
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
  /search/:
    post:
      tags:
      - Decentralized Search
      summary: Search catalog items across catalogs
      description: "Search across the catalogs in decentralized way for filters documentation, you can check it here https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
      operationId: search_catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogFilters'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  '@context':
                    type: object
                  '@graph':
                    type: array
                    items:
                      type: object
              example:
                '@context':
                  xsd: http://www.w3.org/2001/XMLSchema#
                  dcat: http://www.w3.org/ns/dcat#
                  dcatap: http://data.europa.eu/r5r/
                  dcterms: http://purl.org/dc/terms/
                  spdx: http://spdx.org/rdf/terms#
                  foaf: http://xmlns.com/foaf/0.1/
                  skos: http://www.w3.org/2004/02/skos/core#
                  dspace: http://data-space.org/
                '@graph':
                - '@id': https://example.com/catalog/123
                  '@type': dcat:Catalog
                  dcterms:title:
                  - '@language': en
                    '@value': Sample Catalog
                  'other fields': "For all the other fields follow this documentation https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
                - '@id': https://example.com/catalog/124
                  '@type': dcat:Catalog
                  dcterms:title:
                  - '@language': en
                    '@value': Another Sample Catalog
                  'other fields': "For all the other fields follow this documentation https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
                  
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /search-catalog/:
    post:
      tags:
      - Local Search
      summary: Search Local Catalog
      description: "Search the local catalog with dataset list.for filters documentation, you can check it here https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
      operationId: search_catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogFilters'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/ld+json:
              schema:
                type: object
              example:
                'All fields': "For all the fields follow this documentation https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"

        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    CatalogFilters:
      description: "you can find the documentation here https://hiro-microdatacenters-bv.github.io/ds-catalog/docs/index.html#tag/Catalog/operation/get_catalog"
      additionalProperties: true
      type: object
      title: CatalogFilters
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HealthCheck:
      properties:
        status:
          type: string
          title: Status
          examples:
          - OK
      type: object
      required:
      - status
      title: HealthCheck
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError